import { exec } from "child_process";
import { promisify } from "util";
import { existsSync, readFileSync, writeFileSync } from "fs";
import path from "path";
import type { NextRequest } from "next/server";

const execAsync = promisify(exec);

// In Next.js, process.cwd() = the app root (apps/web).
// The monorepo root is two levels up.
const WEB_ROOT = process.cwd();
const REPO_ROOT = path.resolve(WEB_ROOT, "../..");

interface SetupSelections {
  appType: string;
  layoutStyle: string;
  theme: string;
  animations: boolean;
  payingCustomers: boolean;
  deployment: string;
}

type EventType = "step" | "output" | "success" | "error" | "done";

function buildPlan(s: SetupSelections): Array<{ label: string; commands: { cmd: string; cwd: string }[] }> {
  const plan: Array<{ label: string; commands: { cmd: string; cwd: string }[] }> = [];

  const thegridcnAlreadyQueued = { value: false };

  // 1. Init shadcn if needed (non-custom themes)
  if (s.theme !== "custom") {
    plan.push({
      label: "Check shadcn components.json",
      commands: existsSync(path.join(WEB_ROOT, "components.json"))
        ? []
        : [{ cmd: "pnpm dlx shadcn@latest init --defaults", cwd: WEB_ROOT }],
    });
  }

  // 2. Theme install
  if (s.theme === "modern") {
    plan.push({
      label: "Install Modern / Fluid theme (@fluid)",
      commands: [{ cmd: "npx shadcn@latest registry add @fluid", cwd: WEB_ROOT }],
    });
  }

  if (s.theme === "cyberpunk") {
    thegridcnAlreadyQueued.value = true;
    const templateUrl =
      s.layoutStyle === "dashboard"
        ? "https://thegridcn.com/templates/dashboard"
        : s.layoutStyle === "marketing"
        ? "https://thegridcn.com/templates/landing"
        : s.layoutStyle === "analytics"
        ? "https://thegridcn.com/templates/analytics"
        : null;

    plan.push({
      label: `Install CyberPunk / Tron theme (@thegridcn)${templateUrl ? ` [${s.layoutStyle} template]` : ""}`,
      commands: [
        { cmd: "pnpm dlx shadcn@latest registry add @thegridcn", cwd: WEB_ROOT },
        ...(templateUrl ? [{ cmd: `echo "Template reference: ${templateUrl}"`, cwd: WEB_ROOT }] : []),
      ],
    });
  }

  // 3. Animations
  if (s.animations) {
    plan.push({
      label: "Install animate-ui text primitives + motion",
      commands: [
        { cmd: "pnpm dlx shadcn@latest add @animate-ui/primitives-texts-sliding-number", cwd: WEB_ROOT },
        { cmd: "pnpm add motion --filter @repo/web", cwd: REPO_ROOT },
      ],
    });
  }

  // 4. Paying customers (install @thegridcn if not already)
  if (s.payingCustomers && !thegridcnAlreadyQueued.value) {
    plan.push({
      label: "Install @thegridcn billing + pricing components",
      commands: [{ cmd: "pnpm dlx shadcn@latest registry add @thegridcn", cwd: WEB_ROOT }],
    });
  }

  // 5. Deployment configuration
  if (s.deployment && s.deployment !== "none") {
    plan.push({
      label: `Configure ${s.deployment} deployment action`,
      commands: [
        { cmd: `cp .github/workflow-templates/deploy-${s.deployment}.yml .github/workflows/deploy-services.yml`, cwd: REPO_ROOT },
      ],
    });
  }

  // 6. Mutate DESIGN.md
  plan.push({
    label: "Update DESIGN.md — write Active Theme Configuration block",
    commands: [], // handled separately via file mutation
  });

  // 7. Update CONTINUITY.MD
  plan.push({
    label: "Append dated entry to CONTINUITY.MD",
    commands: [], // handled separately via file mutation
  });

  return plan;
}

function mutateDesignMd(s: SetupSelections) {
  const designPath = path.join(REPO_ROOT, "DESIGN.md");
  if (!existsSync(designPath)) return;

  const existing = readFileSync(designPath, "utf-8");
  const marker = "## Active Theme Configuration";

  const block = `${marker}

> Auto-generated by the setup wizard on ${new Date().toISOString().split("T")[0]}. Do not edit manually — re-run the wizard to update.

| Setting | Value |
|---|---|
| App Type | \`${s.appType}\` |
| Layout | \`${s.layoutStyle}\` |
| Theme | \`${s.theme}\` |
| Animations | \`${s.animations ? "yes" : "no"}\` |
| Paying Customers | \`${s.payingCustomers ? "yes" : "no"}\` |
| Deployment | \`${s.deployment}\` |

### Installed Packages
${s.theme === "modern" ? "- `@fluid` — Modern / Fluid shadcn registry\n" : ""}${s.theme === "cyberpunk" || s.payingCustomers ? "- `@thegridcn` — CyberPunk / Tron + billing components\n" : ""}${s.animations ? "- `@animate-ui/primitives-texts-sliding-number` — Sliding number text primitives\n- `motion` — Framer Motion v11\n" : ""}${s.theme === "custom" ? "- No registry installed — custom theme setup required\n" : ""}
---

`;

  // Remove existing block if present, then prepend new one
  const withoutOld = existing.replace(
    new RegExp(`${marker}[\\s\\S]*?---\n\n`, "m"),
    ""
  );

  writeFileSync(designPath, block + withoutOld, "utf-8");
}

function mutateContinuityMd(s: SetupSelections) {
  const continuityPath = path.join(REPO_ROOT, "CONTINUITY.MD");
  const entry = `
## Setup Wizard Run — ${new Date().toISOString()}

**Selections:** App \`${s.appType}\` | Layout \`${s.layoutStyle}\` | Theme \`${s.theme}\` | Animations: ${s.animations} | Paying Customers: ${s.payingCustomers} | Deployment: ${s.deployment}

**Installed:**
${s.theme === "modern" ? "- @fluid registry\n" : ""}${s.theme === "cyberpunk" || s.payingCustomers ? "- @thegridcn registry\n" : ""}${s.animations ? "- @animate-ui/primitives-texts-sliding-number + motion\n" : ""}

**DESIGN.md updated:** Active Theme Configuration block written.

`;

  if (existsSync(continuityPath)) {
    const existing = readFileSync(continuityPath, "utf-8");
    writeFileSync(continuityPath, existing + entry, "utf-8");
  } else {
    writeFileSync(continuityPath, `# CONTINUITY.MD\n${entry}`, "utf-8");
  }
}

export async function POST(request: NextRequest): Promise<Response> {
  // Dev-only guard
  if (process.env.NODE_ENV !== "development") {
    return Response.json(
      { error: "Setup API is only available in development mode." },
      { status: 403 }
    );
  }

  let body: SetupSelections;
  try {
    body = (await request.json()) as SetupSelections;
  } catch {
    return Response.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const encoder = new TextEncoder();

  const stream = new ReadableStream({
    async start(controller) {
      const send = (type: EventType, message: string) => {
        const payload = JSON.stringify({ type, message });
        controller.enqueue(encoder.encode(`data: ${payload}\n\n`));
      };

      try {
        send("step", `Starting configuration for ${body.appType} / ${body.layoutStyle} / ${body.theme}...`);

        const plan = buildPlan(body);

        for (const step of plan) {
          if (step.commands.length === 0) {
            // File mutation step
            send("step", step.label);
            if (step.label.includes("DESIGN.md")) {
              mutateDesignMd(body);
              send("success", "DESIGN.md updated — Active Theme Configuration block written");
            } else if (step.label.includes("CONTINUITY")) {
              mutateContinuityMd(body);
              send("success", "CONTINUITY.MD updated — dated entry appended");
            }
            continue;
          }

          send("step", step.label);

          for (const { cmd, cwd } of step.commands) {
            send("output", `$ ${cmd}`);
            try {
              const { stdout, stderr } = await execAsync(cmd, { cwd, timeout: 120_000 });
              if (stdout.trim()) {
                for (const line of stdout.trim().split("\n").slice(0, 20)) {
                  send("output", line);
                }
              }
              if (stderr.trim()) {
                for (const line of stderr.trim().split("\n").slice(0, 10)) {
                  send("output", line);
                }
              }
              send("success", `✓ ${cmd.split(" ").slice(0, 4).join(" ")}...`);
            } catch (err) {
              const errMsg = err instanceof Error ? err.message : String(err);
              send("error", `Failed: ${errMsg.split("\n")[0]}`);
              // Continue with remaining steps even on individual failures
            }
          }
        }

        send("done", "All steps complete. Your template has been configured.");
      } catch (err) {
        const errMsg = err instanceof Error ? err.message : String(err);
        send("error", `Unexpected error: ${errMsg}`);
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache, no-transform",
      Connection: "keep-alive",
      "X-Accel-Buffering": "no",
    },
  });
}
